{{- if .Values.createClusterRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "argocd-image-updater.fullname" . }}
  labels:
    {{ include "argocd-image-updater.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "argocd-image-updater.fullname" . }}
subjects:
- kind: ServiceAccount
  name: { { include "argocd-image-updater.serviceAccountName" . } }
  namespace: {{ .Release.Namespace }}
{{- end }}
